### ISSUE TITLE
Message Logger clear log dialog not clickable/visible

### ISSUE THREAD

**Issue by Column01** [Metalloriff/UnofficialBetterDiscordPlugins#2]
Seems that the clear the log popup is rather broken. Tried lowering discord zoom and still does this. The buttons in the bottom right are not even clickable either so I can't just click them and I had to delete the data file in the plugins folder to remove my cache (was upwards of 10 MB lol)
![img](https://i.imgur.com/FyjQiRk.png)
(turned up the contrast to make it more visible)

**Comment by Column01** [comment]
This is the error in the console I get that I believe is related to this:
![img](https://i.imgur.com/qZd42r3.png)

**Comment by Murkur** [comment]
> This is the error in the console I get that I believe is related to this:
> ![img](https://camo.githubusercontent.com/65ff350059e11f40abd1628465ac492bb5ddf8fb/68747470733a2f2f692e696d6775722e636f6d2f715a64343272332e706e67)
> EDIT: Maybe not. Those lines in the JS appear to populate the right-click menu and happens when clicking in between messages like this:
> ![img](https://camo.githubusercontent.com/6cc1c6d9f85ba735c8b8d39e1819d8594b8e8e21/68747470733a2f2f692e696d6775722e636f6d2f504155646a78712e706e67)
> EDIT 2: It is the error that does this, just no idea why
> Line 1079 in the plugin:
> ![img](https://camo.githubusercontent.com/3d03efc24645fc53dadd19028a3d1e4712db4b08/68747470733a2f2f692e696d6775722e636f6d2f52506b75676d6c2e706e67)

ever find a solution to this issue?

**Comment by Column01** [comment]
@Murkur Just ended up hacking the plugin to work with electron dialog boxes. It is written asynchronously so it should not stop discord's function when clicked. I believe the issue lies with the library @Metalloriff made and is used a lot in here but I don't have enough knowledge or time to reverse engineer it and find the issue. Maybe at a later date, I will and for all I know it might even just be bad/outdated HTML for the prompt causing it. Leaving the issue open so it can be fixed officially

You can download the modified plugin [here](https://gist.github.com/Column01/d9ebf21b4a5fca2edbbd4f3797416923)

<details>
    <summary>Screenshots (Click me)</summary>
    <img src="https://i.imgur.com/JsuTAnw.png">
    <img src="https://i.imgur.com/Cmrmzr7.png">
</details>

**Comment by Murkur** [comment]
> @Murkur Just ended up hacking the plugin to work with electron dialog boxes. It is written asynchronously so it should not stop discord's function when clicked. I believe the issue lies with the library @Metalloriff made and is used a lot in here but I don't have enough knowledge or time to reverse engineer it and find the issue. Maybe at a later date, I will and for all I know it might even just be bad/outdated HTML for the prompt causing it. Leaving the issue open so it can be fixed officially
> 
> You can download the modified plugin [here](https://gist.github.com/Column01/d9ebf21b4a5fca2edbbd4f3797416923)
> 
> Screenshots (Click me)

AYE thanks thats really helpful

**Comment by Column01** [comment]
@Murkur 
Actually found on the support server for the plugin that someone made a v2 version of the plugin that works properly [here](https://_lighty_.gitlab.io/bdstuff/). You should use that.
Closing this as it appears the plugin has been discontinued
